### ISSUE TITLE
include a "allow video recording" checkbox at talk submission/edition

### ISSUE THREAD

**Issue by maddingue** [book/Act#36]
Suggested by Rolf Langsdorf (YAPC::EU 2012)
It is necessary to ask speakers their permission to record them on video and make the video public. The task could be simplified by adding a checkbox on the talk form, so the organisers already know the speaker who agree on that.

**Comment by elbeho** [comment]
As it is now merged on stable and master (and available on "production" and "test" instances), can we consider this issue "closed"?

**Comment by eseyman** [comment]
Maddingue says to read the commits he links to to see if the issue is fixed but it's beyond my expertise to read 5 commits and make sure they combine to fix one issue. I'm closing this. Feel free to reopen it if you feel this feature is still not present in Act.
